Add functionality for setting additional income for every lord type
VladimirMakeev/D2ModdingToolset pull request #237
Opened 2024-01-05 22:53 UTC by Jarly117

2024-01-06 08:49 UTC, VladimirMakeev commented on Scripts/settings.lua
> +	additionalIncomeWarrior = 0,
Suggestion: put these into their own section like this:
```lua
additionalIncome = {
  warrior = 0,
  mage = 0,
  guildmaster = 0
},
```

2024-01-06 09:34 UTC, UnveN requested changes

2024-01-06 09:34 UTC, UnveN commented on mss32/include/settings.h
> +    std::array<int, 3> additionalLordIncome {};
Using indices is vague - it is not clear which index corresponds to which lord. You better use struct for this purpose and map it to the same struct in settings.lua, like this:
```
struct additionalLordIncome = {
  int warrior;
  int mage;
  int guildmaster;
};
```

2024-01-06 09:34 UTC, UnveN commented on Scripts/settings.lua
> +	additionalIncomeWarrior = 0,
Minor notice - name it `additionalLordIncome` instead of just `additionalIncome` so it becomes clear that the additional income applies to lord types.

2024-01-06 09:34 UTC, UnveN commented on mss32/src/playerincomehooks.cpp
> +    const int goldLord{income->gold + userSettings().additionalLordIncome[static_cast<int>(lordType->data->lordCategory.id)]};
While it appears shorter and smarter, using ids as array indices is bad practice. Ids not necessarily should be sequential and start from 0 (as array indices should be). Better use explicit matching to `additionalLordIncome` struct fields.

Also, `goldLord` variable name looks strange, you could just name it `additionalLordIncome` so it becomes apparent what it actually is.

2024-01-06 12:39 UTC, Jarly117 commented on mss32/src/playerincomehooks.cpp
> +    const int goldLord{income->gold + userSettings().additionalLordIncome[static_cast<int>(lordType->data->lordCategory.id)]};
You mean something like this?
```
int additionalLordIncome {};
const auto lordId = lordType->data->lordCategory.id;
switch (lordId)
{
    case LordId::Warrior: 
        additionalLordIncome = userSettings().additionalLordIncome.warrior;
        break;
    case LordId::Mage:
        additionalLordIncome = userSettings().additionalLordIncome.mage;
        break;
    case LordId::Diplomat:
        additionalLordIncome = userSettings().additionalLordIncome.guildmaster;
        break;
}
```

2024-01-06 20:08 UTC, UnveN commented on mss32/src/playerincomehooks.cpp
> +    const int goldLord{income->gold + userSettings().additionalLordIncome[static_cast<int>(lordType->data->lordCategory.id)]};
@Jarly117 Yep

2024-02-04 11:35 UTC, Jarly117 commented
Okay, fixed all stuff.

2024-02-04 16:35 UTC, merged